### ISSUE TITLE
dataset generate error

### ISSUE THREAD

**Issue by phiedulxp** [shangjingbo1226/AutoNER#11]
```
=== Generating Distant Supervision ===
loading KB...
generate: src/annotation.h:187: void Annotation::loadKBForMatching(const string&, const string&): Assertion `tokens.size() == 2' failed.
```
dict_core.txt not seperate by \t

**Comment by phiedulxp** [comment]
```
  File "preprocess_partial_ner/encode_folder.py", line 191, in <listcomp>
    tmp_lc = [cl_map[tup] for tup in l_c[1:]]
KeyError: 'None'

```

**Comment by shangjingbo1226** [comment]
The dictionary's separator must be \t, since the other whitespace can appear in the entity surface names.

None --> these tokens are not matched as some entity of given types.

S/D stands for the Tie or Break labels are known or unknown. We named it as safe or dangerous at the very beginning of the development.
